version: "3"

x-common-vars: &common-vars
  PG_USERNAME: postgres
  PG_PASSWORD: postgres
  PG_HOST: db
  SELENIUM_HOST: chrome
  SELENIUM_PORT: 4444
  SELENIUM_REMOTE: 1
  DOCKER: 1
x-base-app-settings: &base-app-settings
  depends_on:
    - db
  image: human-essentials
  environment:
    <<: *common-vars
  networks:
    - human-essentials
  volumes:
    - .:/app

services:
  app:
    profiles:
      - build
    <<: *base-app-settings
    build: .
    command: echo Base image only for building
  web:
    <<: *base-app-settings
    ports:
      - "3000:3000"
    command: bash -c "bundle install && bundle exec rails s -p 3000 -b 0.0.0.0"
  worker:
    <<: *base-app-settings
    command: bundle exec rails jobs:work
  db:
    image: "postgres:${POSTGRES_VERSION:-latest}"
    environment:
      - POSTGRES_PASSWORD=postgres
    networks:
      - human-essentials
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
  chrome:
    profiles:
      - chrome
    networks:
      - human-essentials
    # This version should match that of the selenium-webdriver gem (see Gemfile)
    image: selenium/standalone-chrome:4.11.0
    shm_size: 2g
    environment:
      JAVA_OPTS: -Dwebdriver.chrome.whitelistedIps=
    ports:
      - "4444:4444"
    volumes:
      - /dev/shm:/dev/shm

volumes:
  postgres:

networks:
  human-essentials:
